Removed cmdveltopic
clubcapra/capra_web_ui pull request #109
Opened 2022-01-11 21:17 UTC by GLDuval

This topic is no longer used to control the robot in the ROS code. The joyTopic is used for track and flipper control instead

2022-01-11 22:07 UTC, IceSentry requested changes
À part mon petit commentaire, looks good to me.

2022-01-11 22:07 UTC, IceSentry commented on src/renderer/inputSystem/index.ts
> -const deadzone = (value: number): number => {
au lieu de juste le delete je sortirais peut-etre ca dans un module genre, gamepadUtils comme ca si on veux handle dequoi avec les gamepad ca va deja etre la sans avoir à savoir que ca existait par le passé dans git.

2022-01-11 23:03 UTC, GLDuval commented
C'est bon je vais faire ça et pour l'erreur de dependencies est-ce que je les update?

2022-01-12 00:55 UTC, IceSentry commented
Non, c'était pour une bonne intention que j'avais fait ca, mais on a trop de dépendence qui sont abandonné alors je vais juste disable ce check la.

2022-01-12 00:56 UTC, IceSentry commented on package.json
> +    "three": "^0.136.0",
est-ce que c'est volontaire d'avoir ajouter ca dans la PR?

2022-01-12 01:39 UTC, GLDuval commented on package.json
> +    "three": "^0.136.0",
non j'ai essayé d'update les dependencies mais je pense que ça fonctionne toujours pas :)

2022-01-12 01:41 UTC, IceSentry commented on package.json
> +    "three": "^0.136.0",
j'ai enlever le check de master, mais ta branch est en arriere de master. Il faudrait que tu rebase sur master ou que tu merge master dans ta branch

2022-01-12 02:10 UTC, merged

2022-01-12 02:11 UTC, IceSentry commented
bon, github CI semble avoir de la misère, mais le code est correct alors je l'ai merge